# Client configuration for the Excavator system

# System settings
simulation: false  # Set to true if running in simulation mode
inputs: 31  # Note that these values are flipped from the server configuration
outputs: 20

# Network settings
addr: 'localhost'   # Change this to the IP of the excavator if running on different machines
control_port: 5000  # controller data port
sensor_port: 5001   # sensor data port
socket_type: 'client'
protocol: 'UDP'

# Logging
log_level: 'INFO'

# Performance
control_frequency: 20  # Hz, how often to send control data
sensor_frequency: 10  # Hz, how often to send sensor data